# Generated by Django 4.2.3 on 2023-09-23 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DC_Assistant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addname',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
